### ISSUE TITLE
Some scanning errors in visualize

### ISSUE THREAD

**Issue by jpaulm** [noflo/visualize#5]
4 problems that jumped out at me when I tried visualize (added as per discussion with @bergie and @oleksandr):
- It doesn't seem to support the "flow" convention that has been in .fbp notation from the start, e.g. A OUT -> IN B OUT -> IN C
- it doesn't support array notation. e.g. A OUT[0] -> IN B   .  Well, it doesn't object, but it doesn't show the index on the diagram
- ENTER both splits lines and starts the display, so you have to make sure the cursor is at the end of the network definition  - sounds like it needs a Send button!
- It doesn't recognize a process without a component name - for top-down design you have to be able to just say `Gen OUT -> IN Sort OUT...` etc.

Plus one minor one:
- visualize lowercases port names.  However I had understood from @bergie (maybe I misunderstood) that NoFlo only lowercases when generating JSON.  I guess it doesn't matter much as I believe that port names are case-insensitive, but it would be nice to see on the diagram what you actually typed in (same applies to array notation)!

**Comment by jpaulm** [comment]
Re the first bullet - the parser seems to need blanks around the arrows.  They should not be required.

Re the second bullet, now it doesn't seem to like array indexes at all - it used to ignore them...

**Comment by jpaulm** [comment]
@bergie Should this be posted under https://github.com/noflo/fbp/issues ?  If so, we could post it there and close this one.

**Comment by bergie** [comment]
Can you report those to [the fbp parser](https://github.com/noflo/fbp), which visualize uses?

I've used visualize with array indexes pretty recently, so those _should_ work. Same with the flow convention.

![screenshot 2014-10-02 at 19 52 02](https://cloud.githubusercontent.com/assets/3346/4495574/d6575964-4a5c-11e4-8445-34401f1ff01d.png)

So with this I'm assuming the problem is not stating components `NodeName(component)` in your nodes

**Comment by jpaulm** [comment]
Thanks, I'll do some more testing and report any problems to the fbp parser.

Regards,

Paul

**Comment by jpaulm** [comment]
What about https://github.com/noflo/visualize/issues/4 ?  It is now the
only outstanding issue on Visualize, and probably belongs in
https://github.com/noflo/fbp ...?

I have broken #5 down and added most of the parts into
https://github.com/noflo/fbp   .  I noticed that one of the problems I had
with array indexes may have been covered by one of Alex's issues -
https://github.com/noflo/fbp/issues/19 , but I can't duplicate it!

Regards,

Paul
